classifier: !!python/object:sklearn.ensemble._weight_boosting.AdaBoostClassifier
  _sklearn_version: 1.4.2
  algorithm: SAMME.R
  estimator: !!python/object:sklearn.tree._classes.DecisionTreeClassifier
    _sklearn_version: 1.4.2
    ccp_alpha: 0.0
    class_weight: null
    criterion: gini
    max_depth: null
    max_features: null
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    min_samples_leaf: 1
    min_samples_split: 2
    min_weight_fraction_leaf: 0.0
    monotonic_cst: null
    random_state: null
    splitter: best
  estimator_params: !!python/tuple []
  learning_rate: 1.0
  n_estimators: 50
  random_state: null
classifier__estimator__criterion: gini
classifier__estimator__max_depth: 3
classifier__learning_rate: 0.01
