classifier: !!python/object:sklearn.ensemble._gb.GradientBoostingClassifier
  _sklearn_version: 1.3.2
  alpha: 0.9
  ccp_alpha: 0.0
  criterion: friedman_mse
  init: null
  learning_rate: 0.1
  loss: log_loss
  max_depth: 3
  max_features: null
  max_leaf_nodes: null
  min_impurity_decrease: 0.0
  min_samples_leaf: 1
  min_samples_split: 2
  min_weight_fraction_leaf: 0.0
  n_estimators: 100
  n_iter_no_change: null
  random_state: null
  subsample: 1.0
  tol: 0.0001
  validation_fraction: 0.1
  verbose: 0
  warm_start: false
classifier__max_depth: 3
selectkbest__k: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i4
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AwAAAA==
